name: reaktoro

{% set python_version = "3.6" %}

dependencies:
  - boost=1.67
  - cmake
  - invoke
  - ninja
  - numpy
  - pandas
  - pybind11
  - pytest
  - pytest-cpp
  - pytest-datadir
  - pytest-lazy-fixture
  - pytest-regressions
  - pytest-timeout
  - pytest-xdist
  - python={{ python_version }}
  - tabulate
{% if sys.platform.startswith('linux') %}
  - gxx_linux-64=7.3.0
  - libstdcxx-ng
{% endif %}

  # jupyter notebook
  # Packages used to start the jupyter server (plus `nbval` which is for notebook tests).
  - nbval==0.9.0
  - nb_conda==2.2.1
  - ipython==6.4.0

  # Packages used by the kernel where notebooks are run.
  # (They could be added to a separate env, but are kept together here for convenience)
  - ipykernel==4.8.2
  - ipywidgets==7.2.1
  - widgetsnbextension==3.2.1
  - jupyter_contrib_nbextensions==0.5.0

  # Just to pin down other dependencies from `jupyter`. Newer versions are breaking notebook tests.
  - notebook==5.5.0
  - jupyter_client==5.2.3
  - jupyter_core==4.4.0
  - nbconvert==5.3.1

environment:
  {% if os.sys.platform != 'win32' %}

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages

  # Shared library must be in LD_LIBRARY_PATH in order for `reaktoro` to be successfully imported
  LD_LIBRARY_PATH:
    - {{ root }}/artifacts/lib

  {% else %}

  PYTHONPATH:
    - {{ root }}\artifacts\python\Lib\site-packages

  PATH:
    - {{ root }}\artifacts\bin

  {% endif %}
